#include <graphic/renderers/gfxtestrenderpass.h>

#include <graphic/gfx/gfxmanager.h>
#include <graphic/gfx/gfxcontext.h>
#include <graphic/gfx/gfxswapchain.h>
#include <graphic/gfx/gfxview.h>
#include <graphic/gfx/gfxdefaultassets.h>

#include <tmp/shaders/autogen/cpp/PerFrameConsts.h>
#include <tmp/shaders/autogen/cpp/VS_UberShader.h>
#include <tmp/shaders/autogen/cpp/PS_UberShader.h>

void GfxTestRenderPass::Initialize()
{
    bbeProfileFunction();
    m_Name = "GfxTestRenderPass";

    GfxContext& initContext = g_GfxManager.GenerateNewContext(D3D12_COMMAND_LIST_TYPE_DIRECT, "GfxTestRenderPass::Initialize");

    m_RenderPassCB.Initialize<AutoGenerated::PerFrameConsts>();

    GfxDevice& gfxDevice = g_GfxManager.GetGfxDevice();
    gfxDevice.GetCommandListsManager().QueueCommandListToExecute(initContext.GetCommandList(), initContext.GetCommandList().GetType());
}

void GfxTestRenderPass::ShutDown()
{
    m_RenderPassCB.Release();
}

void GfxTestRenderPass::PopulateCommandList()
{
    bbeProfileFunction();

    GfxContext& context = g_GfxManager.GenerateNewContext(D3D12_COMMAND_LIST_TYPE_DIRECT, "GfxTestRenderPass");
    m_Context = &context;
    context.SetRootSignature(GfxDefaultRootSignatures::CBV1_SRV1_IA);

    bbeProfileGPUFunction(context);

    AutoGenerated::PerFrameConsts consts;
    consts.m_ViewProjMatrix = g_GfxView.GetViewProjMatrix();
    m_RenderPassCB.Update(&consts);

    context.StageCBV(m_RenderPassCB, 0, 0);

    GfxPipelineStateObject& pso = context.GetPSO();

    Shaders::VS_UberShaderPermutations vPerms;
    vPerms.VERTEX_FORMAT_Position3f_Normal3f_Texcoord2f_Tangent3f = true;

    const GfxShader& vShader = g_GfxShaderManager.GetShader(vPerms);
    const GfxShader& pShader = g_GfxShaderManager.GetShader(Shaders::PS_UberShaderPermutations{});

    pso.SetVertexShader(vShader);
    pso.SetPixelShader(pShader);

    context.SetRenderTarget(0, g_GfxManager.GetSwapChain().GetCurrentBackBuffer());
    context.SetDepthStencil(g_GfxManager.GetSceneDepthBuffer());

    GfxDefaultAssets::DrawSquidRoom(context, true, 1, 0);
}
