#include <graphic/gfxmanager.h>

#include <graphic/dx12utils.h>
#include <graphic/gfxadapter.h>
#include <graphic/gfxcontext.h>
#include <graphic/gfxrootsignature.h>
#include <graphic/gfxshadermanager.h>
#include <graphic/gfxvertexformat.h>
#include <graphic/gfxdefaulttextures.h>

#include <graphic/renderpasses/gfxtestrenderpass.h>
#include <graphic/renderpasses/gfximguirenderer.h>

void InitializeGraphic()
{
    bbeProfileFunction();

    g_GfxManager.Initialize();
}

void ShutdownGraphic()
{
    bbeProfileFunction();

    g_GfxManager.ShutDown();
}

void UpdateGraphic()
{
    bbeProfileFunction();

    g_GfxManager.RunGraphicTasks();

    if (Keyboard::IsKeyPressed(Keyboard::KEY_J))
    {
        g_GfxManager.DumpGfxMemory();
    }
}

void GfxManager::Initialize()
{
    bbeProfileFunction();

    tf::Taskflow tf;
    
    tf::Task adapterInitTask        = ADD_TF_TASK(tf, g_GfxAdapter.Initialize());
    tf::Task deviceInitTask         = ADD_TF_TASK(tf, m_GfxDevice.Initialize());
    tf::Task cmdListInitTask        = ADD_TF_TASK(tf, m_GfxDevice.GetCommandListsManager().Initialize());
    tf::Task swapChainInitTask      = ADD_TF_TASK(tf, m_SwapChain.Initialize());
    tf::Task rootSigManagerInitTask = ADD_TF_TASK(tf, g_GfxRootSignatureManager.Initialize());
    tf::Task PSOManagerInitTask     = ADD_TF_TASK(tf, g_GfxPSOManager.Initialize());
    tf::Task shaderManagerInitTask  = ADD_TF_TASK(tf, g_GfxShaderManager.Initialize());
    tf::Task vertexFormatsInitTask  = ADD_TF_TASK(tf, g_GfxDefaultVertexFormats.Initialize());

    tf::Task generalGfxInitTask = tf.emplace([&]()
        {
            bbeProfile("General Gfx Init");

            tf::Taskflow generalInitTF;

            tf::Task gfxDefaultTexturesInitTask = generalInitTF.emplace([&]() { g_GfxDefaultTextures.Initialize(); }).name("gfxDefaultTexturesInitTask");
            tf::Task frameParamsCBInitTask = generalInitTF.emplace([&]() { m_FrameParamsCB.Initialize<AutoGenerated::FrameParams>(); }).name("frameParamsCBInitTask");

            g_TasksExecutor.run(generalInitTF).wait();

            m_GfxDevice.Flush(true /* andWait */);
        });

    tf::Task renderPassesInitTask = tf.emplace([&]()
        {
            bbeProfile("Render Passes Construction");

            tf::Taskflow renderPassesInitTF;

            tf::Task testRenderPassInitTask = renderPassesInitTF.emplace([&]() { g_GfxTestRenderPass.Initialize(); }).name("testRenderPassInitTask");
            tf::Task GUIManagerInitTask = renderPassesInitTF.emplace([&]() { g_GfxIMGUIRenderer.Initialize(); }).name("GUIManagerInitTask");

            g_TasksExecutor.run(renderPassesInitTF).wait();

            m_GfxDevice.Flush(true /* andWait */);
        });

    deviceInitTask.succeed(adapterInitTask);
    deviceInitTask.precede(cmdListInitTask, rootSigManagerInitTask, PSOManagerInitTask);
    generalGfxInitTask.succeed(deviceInitTask, cmdListInitTask, rootSigManagerInitTask);
    swapChainInitTask.succeed(deviceInitTask, cmdListInitTask);
    renderPassesInitTask.succeed(swapChainInitTask, rootSigManagerInitTask, PSOManagerInitTask, generalGfxInitTask);

    g_TasksExecutor.run(tf).wait();
}

void GfxManager::ShutDown()
{
    bbeProfileFunction();

    // get swapchain out of full screen before exiting
    BOOL fs = false;
    DX12_CALL(m_SwapChain.Dev()->GetFullscreenState(&fs, NULL));
    if (fs)
        m_SwapChain.Dev()->SetFullscreenState(false, NULL);

    g_GfxPSOManager.ShutDown();
    g_GfxTestRenderPass.ShutDown();
    g_GfxIMGUIRenderer.ShutDown();
    m_FrameParamsCB.Release();
    g_GfxDefaultTextures.ShutDown();

    // we must complete the previous GPU frame before exiting the app
    m_GfxDevice.IncrementAndSignalFence();
    m_GfxDevice.WaitForFence();
    m_GfxDevice.ShutDown();
}

void GfxManager::RunGraphicTasks()
{
    bbeProfileFunction();

    tf::Taskflow tf;

    // consume all gfx commmands multi-threaded
    tf::Task gfxCommandsConsumptionTasks = tf.emplace([&]()
        {
            tf::Taskflow gfxCmdsTF;

            std::vector<std::function<void()>> gfxCommandsToConsume;
            {
                bbeAutoLock(m_GfxCommandsLock);
                gfxCommandsToConsume.swap(m_GfxCommands);
            }
            auto [s,t] = gfxCmdsTF.parallel_for(gfxCommandsToConsume.begin(), gfxCommandsToConsume.end(), [](const std::function<void()>& cmd) { bbeProfile("GfxCommand_MT"); cmd(); });

            g_TasksExecutor.run(gfxCmdsTF).wait();
        }).name("gfxCommandsConsumptionTasks");

    tf::Task beginFrameTask           = ADD_TF_TASK(tf, BeginFrame());
    tf::Task transitionBackBufferTask = ADD_TF_TASK(tf, TransitionBackBufferForPresent());
    tf::Task endFrameTask             = ADD_TF_TASK(tf, EndFrame());
    tf::Task renderPassesRenderTasks  = ADD_TF_TASK(tf, RunRenderPasses());

    gfxCommandsConsumptionTasks.precede(beginFrameTask);
    beginFrameTask.precede(renderPassesRenderTasks);
    transitionBackBufferTask.succeed(renderPassesRenderTasks);
    endFrameTask.succeed(transitionBackBufferTask);

    g_TasksExecutor.run(tf).wait();
}

void GfxManager::RunRenderPasses()
{
    bbeProfileFunction();

    tf::Taskflow tf;

    tf::Task testRenderPass  = ADD_TF_TASK(tf, g_GfxTestRenderPass.Render(m_GfxDevice.GenerateNewContext(D3D12_COMMAND_LIST_TYPE_DIRECT, "TestRenderPass")));
    tf::Task IMGUIRenderPass = ADD_TF_TASK(tf, g_GfxIMGUIRenderer.Render(m_GfxDevice.GenerateNewContext(D3D12_COMMAND_LIST_TYPE_DIRECT, "IMGUIRenderPass")));

    IMGUIRenderPass.succeed(testRenderPass);

    g_TasksExecutor.run(tf).wait();
}

void GfxManager::BeginFrame()
{
    bbeProfileFunction();

    // wait for GPU to be done with previous frame
    m_GfxDevice.WaitForFence();

    // check for DXGI_ERRORs on all GfxDevices
    m_GfxDevice.CheckStatus();

    UpdateFrameParamsCB();
}

void GfxManager::EndFrame()
{
    bbeProfileFunction();

    m_GfxDevice.Flush();
    m_SwapChain.Present();
    m_GfxDevice.IncrementAndSignalFence();
}

void GfxManager::DumpGfxMemory()
{
    WCHAR* statsString = NULL;

    D3D12MA::Allocator& allocator = m_GfxDevice.GetD3D12MemoryAllocator();

    allocator.BuildStatsString(&statsString, allocator.GetD3D12Options().ResourceHeapTier == D3D12_RESOURCE_HEAP_TIER_2);

    const std::string dumpFilePath = StringFormat("..\\bin\\GfxMemoryDump_%s.json", GetTimeStamp().c_str());
    const bool IsReadMode = false;
    CFileWrapper outFile{ dumpFilePath, IsReadMode };
    fprintf(outFile, "%ls", statsString);

    allocator.FreeStatsString(statsString);
}

void GfxManager::TransitionBackBufferForPresent()
{
    bbeProfileFunction();

    GfxContext& context = m_GfxDevice.GenerateNewContext(D3D12_COMMAND_LIST_TYPE_DIRECT, "TransitionBackBufferForPresent");
    SetD3DDebugName(context.GetCommandList().Dev(), "TransitionBackBufferForPresent");

    m_SwapChain.TransitionBackBufferForPresent(context);
}

void GfxManager::UpdateFrameParamsCB()
{
    AutoGenerated::FrameParams params;
    params.m_FrameNumber = g_System.GetSystemFrameNumber();
    params.m_CurrentFrameTime = (float)g_System.GetCappedFrameTimeMs();
    //params.m_PreviousFrameTime = g_System.GetCappedPrevFrameTimeMs();

    m_FrameParamsCB.Update(&params);
}
